### ISSUE TITLE
core -- ML model assembler 

### ISSUE THREAD

**Issue by zhuyuecai** [mcgill-cpslab/spiral#12]
### Description

A function that takes two ML models, extract the layers from them, stack the layers according to the original sequence
 and the input sequence to form a new ML model. 
For example, input 1 is a 3 layers FNN and input 2 is a 2 layer RNN, then this function return a stacked model with 3 FNN layers and 2 RNN layers.

this is the planning phase for this feature

### DOD
* investigate how we can achieve this. 
* create issues for its development works

**Comment by fuyuanlyu** [comment]
After investigation, I find that it is easy to achieve this on various frameworks explicitly. Having doubts whether we should write an example about it

**Comment by fuyuanlyu** [comment]
After discussion, we will use examples to achieve this.
