### ISSUE TITLE
DTDG storage model main code

### ISSUE THREAD

**Issue by zhuyuecai** [mcgill-cpslab/spiral#6]
### Description
A wrap of DGL static graph model, DTDG should be an array of multiple DGL static graph.

### Definition of done
source code and test cases for the DTDG storage model, this should support tensorflow and pytorch as backend.

**Comment by AnyLeoPeace** [comment]
Hi Yuecai, I suggest using https://ogb.stanford.edu/docs/linkprop/#ogbl-citation2 or https://ogb.stanford.edu/docs/nodeprop/#ogbn-arxiv to build a demo dataset. 

You can also find many other similar graph data sets on OGB (https://ogb.stanford.edu).
